"""Tests for vdjtools.stats.inext — numerically pinned to the iNEXT R package.

The oracle values below are the DETERMINISTIC point estimates of iNEXT 3.0.2 on
the ``spider`` abundance vectors (``Girdled`` / ``Logged``), regenerated by
``tests/assets/inext_oracle.R`` and committed as ``tests/assets/spider_*.txt``.
The tests read the committed vectors + hardcoded constants only — R is NOT
required at test time. Confidence intervals are RNG-dependent, so only their
structure is asserted (plus one loose se sanity check).
"""
import math
from pathlib import Path

import numpy as np
import polars as pl
import pytest

from vdjtools import stats

ASSETS = Path(__file__).resolve().parent.parent / "assets"


def _load(name: str) -> np.ndarray:
    text = (ASSETS / name).read_text()
    return np.array([int(t) for t in text.split()], dtype=np.int64)


@pytest.fixture(scope="module")
def girdled() -> np.ndarray:
    return _load("spider_girdled.txt")


@pytest.fixture(scope="module")
def logged() -> np.ndarray:
    return _load("spider_logged.txt")


RTOL = 1e-4  # point estimates are deterministic in iNEXT


# --------------------------------------------------------------------------- #
# DataInfo: n, S_obs, f1, f2, and observed sample coverage Chat(n)
# --------------------------------------------------------------------------- #
def test_datainfo_girdled(girdled):
    assert int(girdled.sum()) == 168
    assert girdled.size == 26
    assert int(np.count_nonzero(girdled == 1)) == 12
    assert int(np.count_nonzero(girdled == 2)) == 4
    assert math.isclose(stats.sample_coverage(girdled), 0.9288554, rel_tol=RTOL)


def test_datainfo_logged(logged):
    assert int(logged.sum()) == 252
    assert logged.size == 37
    assert int(np.count_nonzero(logged == 1)) == 14
    assert int(np.count_nonzero(logged == 2)) == 4
    assert math.isclose(stats.sample_coverage(logged), 0.9446, rel_tol=RTOL)


# --------------------------------------------------------------------------- #
# Coverage Chat(m)
# --------------------------------------------------------------------------- #
def test_coverage_girdled(girdled):
    assert math.isclose(stats.sample_coverage(girdled, 100), 0.9072004, rel_tol=RTOL)
    assert math.isclose(stats.sample_coverage(girdled, 200), 0.9373713, rel_tol=RTOL)
    assert math.isclose(stats.sample_coverage(girdled, 336), 0.9635701, rel_tol=RTOL)


def test_coverage_frame(girdled):
    frame = stats.sample_coverage(girdled, [100, 200, 336])
    assert frame.columns == ["m", "sample_coverage"]
    assert math.isclose(frame["sample_coverage"][1], 0.9373713, rel_tol=RTOL)


# --------------------------------------------------------------------------- #
# Asymptotic (Chao1 / Chao-Wang-Jost Shannon / MVUE Simpson)
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("q,expected", [(0, 43.892857), (1, 13.826253), (2, 8.174825)])
def test_asymptotic_girdled(girdled, q, expected):
    row = stats.asymptotic_diversity(girdled, q=q, se=False)
    assert math.isclose(row["estimator"][0], expected, rel_tol=RTOL)


@pytest.mark.parametrize("q,expected", [(0, 61.402778), (1, 16.337069), (2, 6.920350)])
def test_asymptotic_logged(logged, q, expected):
    row = stats.asymptotic_diversity(logged, q=q, se=False)
    assert math.isclose(row["estimator"][0], expected, rel_tol=RTOL)


# --------------------------------------------------------------------------- #
# Size-based rarefaction/extrapolation qD
# --------------------------------------------------------------------------- #
# (m, q) -> expected qD, from iNEXT size_based table (Girdled).
GIRDLED_SIZE = {
    (100, 0): 20.459426, (100, 1): 11.266546, (100, 2): 7.627561,
    (168, 0): 26.000000, (168, 1): 12.059650, (168, 2): 7.840000,
    (200, 0): 28.141739, (200, 1): 12.303742, (200, 2): 7.891717,
    (336, 0): 34.730730, (336, 1): 13.016966, (336, 2): 8.003912,
}


def test_size_based_girdled(girdled):
    df = stats.inext(girdled, q=(0, 1, 2), sizes=[100, 168, 200, 336], se=False)
    got = {(r["m"], r["order_q"]): r["qD"] for r in df.iter_rows(named=True)}
    for key, expected in GIRDLED_SIZE.items():
        assert math.isclose(got[key], expected, rel_tol=RTOL), f"{key}: {got[key]}"


def test_size_based_girdled_methods(girdled):
    df = stats.inext(girdled, q=0, sizes=[100, 168, 200, 336], se=False).sort("m")
    assert df["method"].to_list() == [
        "rarefaction", "observed", "extrapolation", "extrapolation"]
    # sample_coverage attached per depth
    assert math.isclose(
        df.filter(pl.col("m") == 200)["sample_coverage"][0], 0.9373713, rel_tol=RTOL)


def test_size_based_logged_m100(logged):
    df = stats.inext(logged, q=(0, 1, 2), sizes=[100], se=False)
    got = {r["order_q"]: r["qD"] for r in df.iter_rows(named=True)}
    assert math.isclose(got[0], 25.642342, rel_tol=RTOL)
    assert math.isclose(got[1], 12.648884, rel_tol=RTOL)
    assert math.isclose(got[2], 6.533542, rel_tol=RTOL)


# --------------------------------------------------------------------------- #
# Coverage-based R/E (estimateD @ C = 0.95)
# --------------------------------------------------------------------------- #
def test_estimate_d_coverage_girdled(girdled):
    df = stats.estimate_d(girdled, base="coverage", level=0.95, q=(0, 1, 2), se=False)
    assert math.isclose(df["m"][0], 256.53, rel_tol=1e-3)
    got = {r["order_q"]: r["qD"] for r in df.iter_rows(named=True)}
    assert math.isclose(got[0], 31.317857, rel_tol=RTOL)
    assert math.isclose(got[1], 12.655438, rel_tol=RTOL)
    assert math.isclose(got[2], 7.952402, rel_tol=RTOL)


def test_estimate_d_coverage_logged(logged):
    df = stats.estimate_d(logged, base="coverage", level=0.95, q=(0, 1, 2), se=False)
    assert math.isclose(df["m"][0], 297.33, rel_tol=1e-3)
    got = {r["order_q"]: r["qD"] for r in df.iter_rows(named=True)}
    assert math.isclose(got[0], 39.390278, rel_tol=RTOL)
    assert math.isclose(got[1], 14.672108, rel_tol=RTOL)
    assert math.isclose(got[2], 6.785245, rel_tol=RTOL)


def test_inext_coverage_matches_estimate_d(girdled):
    # Passing an explicit coverage to inext_coverage matches estimate_d at that C.
    df = stats.inext_coverage(girdled, q=0, coverages=[0.95], se=False)
    assert math.isclose(df["qD"][0], 31.317857, rel_tol=RTOL)
    assert df["method"][0] == "extrapolation"


def test_estimate_d_size_default_is_observed(girdled):
    df = stats.estimate_d(girdled, base="size", q=(0, 1, 2), se=False)
    assert (df["m"] == 168.0).all()
    got = {r["order_q"]: r["qD"] for r in df.iter_rows(named=True)}
    assert got[0] == 26.0
    assert math.isclose(got[1], 12.059650, rel_tol=RTOL)


# --------------------------------------------------------------------------- #
# Confidence-interval STRUCTURE (bounds only — RNG differs from R)
# --------------------------------------------------------------------------- #
def test_ci_structure_size(girdled):
    df = stats.inext(girdled, q=(0, 1, 2), sizes=[50, 100, 168, 250], nboot=30, seed=0)
    assert (df["qD_lo"] <= df["qD"]).all()
    assert (df["qD"] <= df["qD_hi"]).all()
    assert (df["qD_lo"] >= 0.0).all()
    assert ((df["sample_coverage"] >= 0.0) & (df["sample_coverage"] <= 1.0)).all()


def test_ci_structure_coverage(girdled):
    df = stats.inext_coverage(girdled, q=(0, 1, 2), coverages=[0.9, 0.95], nboot=30, seed=0)
    assert (df["qD_lo"] <= df["qD"]).all()
    assert (df["qD"] <= df["qD_hi"]).all()
    assert (df["qD_lo"] >= 0.0).all()


def test_bootstrap_se_loose(girdled):
    # iNEXT (nboot=200, seed=0) reports se ~ 1.626 for Girdled size m=100, q=0.
    # numpy's RNG differs, so only require agreement within ~40%.
    df = stats.inext(girdled, q=0, sizes=[100], nboot=200, seed=0)
    se = (df["qD_hi"][0] - df["qD"][0]) / 1.959964
    assert 0.6 * 1.626 <= se <= 1.4 * 1.626


# --------------------------------------------------------------------------- #
# Hand-checkable unit tests
# --------------------------------------------------------------------------- #
def test_inext_q0_interpolation_pins_two():
    # Cross-check against the existing rarefaction pin: [1,1,1,1] has n=4, S=4,
    # E[S] at subsample m=2 is 4*(1 - C(3,2)/C(4,2)) = 4*(1 - 3/6) = 2.0.
    df = stats.inext([1, 1, 1, 1], q=0, sizes=[2], se=False)
    assert df["method"][0] == "rarefaction"
    assert math.isclose(df["qD"][0], 2.0, rel_tol=1e-12)


def test_chat_tiny_vector():
    # x = [1, 1, 2]: n=4, f1=2, f2=1. Chat(n) = 1 - (f1/n)*((n-1)*f1/((n-1)*f1+2*f2))
    #   = 1 - (2/4)*((3*2)/(3*2+2)) = 1 - 0.5*(6/8) = 1 - 0.375 = 0.625.
    assert math.isclose(stats.sample_coverage([1, 1, 2]), 0.625, rel_tol=1e-12)


def test_q2_closed_form_hand():
    # x = [2, 2]: n=4. D2(m) = 1/(1/m + (m-1)/m * sum X(X-1)/(n(n-1))).
    # sum X(X-1) = 2+2 = 4; n(n-1) = 12; term = 4/12 = 1/3.
    # At m=n=4 (observed): plug-in inverse-Simpson = 1/((0.5)^2+(0.5)^2) = 2.0.
    df = stats.inext([2, 2], q=2, sizes=[4], se=False)
    assert math.isclose(df["qD"][0], 2.0, rel_tol=1e-12)
    # At m=2: 1/(1/2 + (1/2)*(1/3)) = 1/(0.5 + 0.16667) = 1.5.
    df2 = stats.inext([2, 2], q=2, sizes=[2], se=False)
    assert math.isclose(df2["qD"][0], 1.5, rel_tol=1e-12)


def test_observed_row_equals_plugin(girdled):
    # The observed (m=n) row must equal the plug-in Hill number of each order.
    df = stats.inext(girdled, q=(0, 1, 2), sizes=[168], se=False)
    p = girdled / girdled.sum()
    plugin = {
        0: float((p > 0).sum()),
        1: float(np.exp(-np.sum(p * np.log(p)))),
        2: float(1.0 / np.sum(p**2)),
    }
    for r in df.iter_rows(named=True):
        assert r["method"] == "observed"
        assert math.isclose(r["qD"], plugin[r["order_q"]], rel_tol=1e-12)


def test_q0_monotone_nondecreasing(girdled):
    # Richness (q=0) is non-decreasing in sampling depth m.
    df = stats.inext(girdled, q=0, knots=25, se=False).sort("m")
    vals = df["qD"].to_list()
    assert all(b >= a - 1e-9 for a, b in zip(vals, vals[1:]))


def test_dataframe_input_uses_duplicate_count(girdled):
    # A clonotype DataFrame with duplicate_count yields the same curve as the vector.
    frame = pl.DataFrame({"duplicate_count": girdled})
    a = stats.inext(girdled, q=0, sizes=[100], se=False)["qD"][0]
    b = stats.inext(frame, q=0, sizes=[100], se=False)["qD"][0]
    assert math.isclose(a, b, rel_tol=1e-12)
